import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from 'next/font/google';
import Footer from './components/footer';
import Header from './components/header';
import './globals.css';
import './page.module.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
      <script src='bootstrap/dist/js/bootstrap.min.js'></script>
    </html>
  )
}
